apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      containers:
        - name: app
          image: node:18
          command: ["node", "server.js"]
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/mydatabase
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
    tier: frontend
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
