apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
      tier: cicd
  template:
    metadata:
      labels:
        app: jenkins
        tier: cicd
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
            - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
    tier: cicd
  ports:
    - port: 8080
      targetPort: 8080
    - port: 50000
      targetPort: 50000
  type: NodePort
